services:
  - sqlite

env:
  - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
  - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0
  - ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0
  - ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.5
  - ILLUMINATE_VERSION=6.0.* PHPUNIT_VERSION=^8.3

matrix:
  fast_finish: true
  include:
    # Don't test Laravel versions higher than 5.5 on PHP 7.0.12
    - php: 7.0.12
      env: ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 TESTBENCH_VERSION=3.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0 TESTBENCH_VERSION=3.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.* PHPUNIT_VERSION=~7.0 TESTBENCH_VERSION=3.7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.8.* PHPUNIT_VERSION=^7.5 TESTBENCH_VERSION=3.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=6.0.* PHPUNIT_VERSION=^8.3 TESTBENCH_VERSION=4.0.*

sudo: false

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install: travis_retry composer update --no-interaction --prefer-dist --no-suggest

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit --verbose