language: php

php:
  - 7.0.12
  - 7.1
  - 7.2

services:
  - sqlite

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit --verbose